# Generated by Django 3.1 on 2021-03-31 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0002_auto_20210210_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoStructPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('ALGO', 'ALGO'), ('STRUCT', 'STRUCT')], default='ALGO', max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=4096)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alg_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_struct_posts', models.ManyToManyField(blank=True, related_name='user_favorite', to='algorithmixblog.AlgoStructPost')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='related_blog_posts', to='algorithmixblog.BlogPostCategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameModel(
            old_name='AlgorithmPostCategory',
            new_name='AlgoStructPostCategory',
        ),
        migrations.DeleteModel(
            name='AlgorithmPost',
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='blog_posts',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to='algorithmixblog.BlogPost'),
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='algostructpost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='related_algo_struct_posts', to='algorithmixblog.AlgoStructPostCategory'),
        ),
        migrations.AddField(
            model_name='algostructpost',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_algo_struct_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='algostructpost',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_algo_struct_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
