# Generated by Django 3.1 on 2021-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0003_auto_20210331_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlgoStructPostCategory',
            new_name='AlgoStructPostTag',
        ),
        migrations.RenameModel(
            old_name='BlogPostCategory',
            new_name='BlogPostTag',
        ),
        migrations.RemoveField(
            model_name='algostructpost',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='algostructpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='related_algo_struct_posts', to='algorithmixblog.AlgoStructPostTag'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='related_blog_posts', to='algorithmixblog.BlogPostTag'),
        ),
    ]
