# Generated by Django 3.1 on 2021-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0004_auto_20210331_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='algostructpost',
            name='cover_img_link',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
