# Generated by Django 3.1 on 2021-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0005_algostructpost_cover_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_img_link',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
