# Generated by Django 3.1 on 2021-04-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0006_blogpost_cover_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
