# Generated by Django 3.1 on 2021-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0007_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='algostructpost',
            name='description',
            field=models.CharField(default='No description provided.', max_length=1024),
        ),
        migrations.AddField(
            model_name='blogpostcomment',
            name='description',
            field=models.CharField(default='No description provided.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='algostructpost',
            name='text',
            field=models.CharField(max_length=65536),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='text',
            field=models.CharField(max_length=65536),
        ),
    ]
