# Generated by Django 3.1 on 2021-04-20 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0008_auto_20210414_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttag',
            name='post_type',
            field=models.CharField(blank=True, choices=[('BLOGPOST', 'BLOGPOST'), ('ALGOSTRUCTPOST', 'ALGOSTRUCTPOST')], max_length=32),
        ),
        migrations.AlterField(
            model_name='algostructpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='algstr_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='bp_liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_comments', to='algorithmixblog.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='text',
            field=models.CharField(max_length=8388608),
        ),
        migrations.CreateModel(
            name='AlgoStructPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='No description provided.', max_length=1024)),
                ('text', models.CharField(max_length=524288)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algstr_user_comments', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(blank=True, related_name='algstr_liked_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algstr_comments', to='algorithmixblog.blogpost')),
            ],
        ),
    ]
