# Generated by Django 3.1 on 2021-06-14 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0010_auto_20210421_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algostructpostcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='algostructpostcomment',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='algostructpostcomment',
            name='post',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='cover_img_link',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.RemoveField(
            model_name='blogposttag',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='userfavorites',
            name='fav_algstr_posts',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.CharField(max_length=20480),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='blogpost_liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='algorithmixblog.blogpost'),
        ),
        migrations.DeleteModel(
            name='AlgoStructPost',
        ),
        migrations.DeleteModel(
            name='AlgoStructPostComment',
        ),
        migrations.DeleteModel(
            name='AlgoStructPostTag',
        ),
    ]
