# Generated by Django 3.1 on 2021-06-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0011_auto_20210614_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='cover',
            new_name='cover_url',
        ),
    ]
