# Generated by Django 3.1 on 2021-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0012_auto_20210615_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.CharField(max_length=40960),
        ),
    ]
