# Generated by Django 3.1 on 2021-06-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0013_auto_20210617_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='description',
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
