# Generated by Django 3.1 on 2021-07-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0014_auto_20210619_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcomment',
            old_name='likes',
            new_name='like_count',
        ),
    ]
