# Generated by Django 3.1 on 2021-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0016_auto_20210712_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='No info given.', max_length=1024),
        ),
    ]
