# Generated by Django 3.1 on 2021-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0017_auto_20210713_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=1024),
        ),
    ]
