# Generated by Django 3.1 on 2021-07-13 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0021_auto_20210713_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='favorers',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favorers',
            field=models.ManyToManyField(blank=True, related_name='favorite_blogposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
