# Generated by Django 3.1 on 2021-07-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0022_auto_20210713_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='algorithmixblog.blogpostcomment'),
        ),
    ]
