# Generated by Django 3.1 on 2021-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0023_blogpostcomment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='had_reference',
            field=models.BooleanField(default=False),
        ),
    ]
