# Generated by Django 3.1 on 2021-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0025_blogpost_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='is_censored',
            field=models.BooleanField(default=False),
        ),
    ]
