# Generated by Django 3.1 on 2021-07-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0026_blogpostcomment_is_censored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_public',
            new_name='is_private',
        ),
    ]
