# Generated by Django 3.1 on 2021-07-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmixblog', '0028_auto_20210719_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='like_count',
        ),
    ]
